# Allow build scripts for trusted dependencies
# - https://pnpm.io/settings#allowbuilds
allowBuilds:
  esbuild: true
  unrs-resolver: true

# Prevent installation of packages newer than 7 days
# to mitigate supply chain risks
# - https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@upleveled/*'
  - eslint-config-upleveled
  - stylelint-config-upleveled
